module.exports = {
    "hostImg": "https://betapic.uhomecp.com/",
    "hostImg1": "https://betapic.uhomecp.com/",
    "hostPrime": "",
    "platform": "goltebk",
    "socketServer": "https://beta.uhomecp.com",
    "loginSocketServer": "beta.uhomecp.com",
    "tabIcon": "",
    "unifyContext": "",
    "envMap": {
        "defaultApp": {
            "appName": "寻常生活",
            "appNameColor": "#333",
            "slogan": "发现生活无限可能",
            "theme": "#FF5E5E",
            "sloganColor": "#666",
            "bonuseSysName": "积分商城",
            "coinName": "积分",
            "logoIcon": "https://betapic.uhomecp.com/logo/uhome_new.png",
            "openBtnBackground": "#FF5E5E",
            "shareFooterBackground": "#fff",
            "downloadUrl": "https://beta.uhomecp.com/uhome_download.html",
            "email": "segi@segimail.com",
            "tel": "0755-86700725",
            "cancelAccountTip": "“我的”->“设置”->“注销账号”"
        },
        "SEGI": {
            "appName": "寻常生活",
            "appNameColor": "#333",
            "company": "深圳市四格互联信息技术有限公司",
            "companyShortName": "四格互联",
            "developer": "深圳市四格互联信息技术有限公司",
            "corporation": "梁林志",
            "slogan": "发现生活无限可能",
            "sloganColor": "#666",
            "theme": "#FF5E5E",
            "bonuseSysName": "积分商城",
            "coinName": "积分",
            "logoIcon": "https://betapic.uhomecp.com/logo/uhome_new.png",
            "openBtnBackground": "#fcbd30",
            "shareFooterBackground": "#fff",
            "downloadUrl": "https://beta.uhomecp.com/uhome_download.html",
            "email": "luowen@segimail.com",
            "tel": "0755-86700725",
            "wxappid": "wxf4f712f72a013ff9",
            "cancelAccountTip": "“消息”->“设置”->“注销账户”"
        },
        "SEGIBK": {
            "appName": "企云助手",
            "appNameColor": "#3e5de1",
            "slogan": "",
            "sloganColor": "#666",
            "bonuseSysName": "",
            "coinName": "",
            "logoIcon": "https://betapic.uhomecp.com/logo/segibk_new.png",
            "openBtnBackground": "#3e5de1",
            "shareFooterBackground": "#fff",
            "downloadUrl": "https://beta.uhomecp.com/uhome_download_admin.html",
            "company": "深圳市四格互联信息技术有限公司",
            "corporation": "梁林志",
            "tel": "0755-86967641",
            "email": "luowen@segimail.com",
            "developer": "深圳市四格互联信息技术有限公司",
            "theme": "#3d70ef",
            "cancelAccountTip": "“我的”->“设置”->“注销账户”"
        },
        "CMHK": {
            "appName": "招商到家汇",
            "appNameColor": "#333",
            "slogan": "纷享美好社区生活",
            "sloganColor": "#666",
            "bonuseSysName": "积分商城",
            "coinName": "到家币",
            "logoIcon": "http://vippic.cmpmc.com/logo/cmhk.png",
            "openBtnBackground": "#149bfe",
            "shareFooterBackground": "#fff",
            "downloadUrl": "http://download.cmpmc.com/download.htm"
        },
        "HUARUN": {
            "appName": "悦家",
            "appNameColor": "#333",
            "slogan": "开启智慧生活",
            "sloganColor": "#666",
            "bonuseSysName": "积分商城",
            "coinName": "积分",
            "logoIcon": "https://betapic.uhomecp.com/logo/huarun.png",
            "openBtnBackground": "#fcbd30",
            "shareFooterBackground": "#fff",
            "downloadUrl": "http://android.uhomecp.com/huarun/download.html"
        },
        "HUARUNBK": {
            "appName": "悦心",
            "company": "华润物业科技服务有限公司",
            "companyShortName": "华润物业科技服务有限公司",
            "appNameColor": "#333",
            "slogan": "",
            "sloganColor": "#666",
            "bonuseSysName": "",
            "coinName": "",
            "logoIcon": "https://betapic.uhomecp.com/logo/huarunbk.png",
            "openBtnBackground": "#fcbd30",
            "shareFooterBackground": "#fff",
            "downloadUrl": "http://android.uhomecp.com/huarun/download_admin.html"
        },
        "SHENGQUAN": {
            "appName": "桔邻",
            "appNameColor": "#333",
            "slogan": "远亲不如近邻，近邻在用桔邻",
            "sloganColor": "#666",
            "bonuseSysName": "积分商城",
            "coinName": "积分",
            "logoIcon": "https://betapic.uhomecp.com/logo/shengquan.png",
            "openBtnBackground": "#f18e1e",
            "shareFooterBackground": "#fff",
            "downloadUrl": "http://android.uhomecp.com/shengquan/download.html"
        },
        "SYWY": {
            "appName": "深到家",
            "company": "深业物业",
            "companyShortName": "深业物业",
            "developer": "深业物业集团有限公司",
            "corporation": "肖武春",
            "tel": "83326118",
            "email": "admin@sywy.net",
            "appNameColor": "#fff",
            "slogan": "",
            "sloganColor": "#fff",
            "theme": "#d7000f",
            "bonuseSysName": "",
            "coinName": "",
            "logoIcon": "https://betapic.uhomecp.com/logo/sywy.png",
            "openBtnBackground": "#d7000f",
            "shareFooterBackground": "rgba(0,0,0,0.8)",
            "downloadUrl": "http://android.uhomecp.com/shengye/download.html"
        },
        "SYWYBK": {
            "appName": "业委汇",
            "appNameColor": "#333",
            "company": "深业物业",
            "companyShortName": "深业物业",
            "corporation": "唐玮",
            "tel": "13510551322",
            "email": "5759593@qq.com",
            "developer": "深业物业集团有限公司",
            "slogan": "",
            "sloganColor": "#666",
            "bonuseSysName": "",
            "coinName": "",
            "logoIcon": "https://betapic.uhomecp.com/logo/sywybk.png",
            "openBtnBackground": "#3e5de1",
            "shareFooterBackground": "#fff",
            "downloadUrl": "http://android.uhomecp.com/shengye/download_admin.html",
            "theme": "#d7000f",
            "cancelAccountTip": "“我的”->“设置”->“注销账号”"
        },
        "SYWYCHKBK": {
            "appName": "深业城市管家",
            "appNameColor": "#333",
            "company": "深业物业",
            "companyShortName": "深业物业",
            "corporation": "唐玮",
            "tel": "13510551322",
            "email": "5759593@qq.com",
            "developer": "深业物业集团有限公司",
            "slogan": "",
            "sloganColor": "#666",
            "bonuseSysName": "",
            "coinName": "",
            "logoIcon": "https://betapic.uhomecp.com/logo/sycsgj.png",
            "openBtnBackground": "#3e5de1",
            "shareFooterBackground": "#fff",
            "downloadUrl": "http://android.uhomecp.com/shengye/download_admin2.html"
        },
        "ITGWYBK": {
            "appName": "国贸星标",
            "company": "厦门国贸物业管理有限公司",
            "companyShortName": "国贸物业",
            "appNameColor": "#333",
            "slogan": "",
            "sloganColor": "#666",
            "bonuseSysName": "",
            "coinName": "",
            "logoIcon": "https://betapic.uhomecp.com/logo/itgwybk.png",
            "openBtnBackground": "#fcbd30",
            "shareFooterBackground": "#fff",
            "downloadUrl": "http://android.uhomecp.com/itgwy/download_admin.html"
        },
        "RONGHUI": {
            "appName": "小汇当家",
            "company": "融汇物业服务有限公司",
            "companyShortName": "融汇物业",
            "developer": "重庆融汇物业管理有限公司",
            "corporation": "黄威林",
            "appNameColor": "#333",
            "slogan": "",
            "sloganColor": "#666",
            "bonuseSysName": "积分商城",
            "coinName": "积分",
            "logoIcon": "https://betapic.uhomecp.com/logo/ronghui.png",
            "openBtnBackground": "#333",
            "shareFooterBackground": "#fff",
            "downloadUrl": "http://android.uhomecp.com/ronghui/download.html",
            "theme": "#d0b988",
            "email": "lubi@ronghui.com",
            "tel": "023-62595518",
            "wxappid": "wxe5516ca4069dd016"
        },
        "SANY": {
            "appName": "SANY+",
            "appNameColor": "#333",
            "slogan": "发现生活无限可能",
            "company": "长沙盛源房地产有限公司",
            "companyShortName": "盛源房产",
            "theme": "#FF5E5E",
            "sloganColor": "#666",
            "bonuseSysName": "积分商城",
            "coinName": "积分",
            "logoIcon": "https://static-imc.sanygroup.com/logo/sany.png",
            "openBtnBackground": "#E60012",
            "shareFooterBackground": "#fff",
            "downloadUrl": "https://static-imc.sanygroup.com/app/download.html",
            "tel": "0731-81854326",
            "developer": "长沙盛源房地产有限公司",
            "corporation": "梁林河",
            "email": "zhangmj9@sany.com.cn",
            "cancelAccountTip": "“我的”->“注销账户”"
        },
        "ISANY": {
            "appName": "ISANY",
            "appNameColor": "#333",
            "slogan": "发现生活无限可能",
            "company": "长沙盛源房地产有限公司",
            "companyShortName": "盛源房产",
            "theme": "#0068FE",
            "sloganColor": "#666",
            "bonuseSysName": "积分商城",
            "coinName": "积分",
            "openBtnBackgroup": "#0068FE"
        },
        "GANGLIAN": {
            "appName": "港联",
            "company": "城投四新之光",
            "companyShortName": "城投四新之光",
            "appNameColor": "#333",
            "slogan": "城投四新之光 智慧生活新起点 ",
            "sloganColor": "#666",
            "bonuseSysName": "",
            "coinName": "",
            "logoIcon": "https://betapic.uhomecp.com/logo/ganglian.png",
            "tel": "027-68850515",
            "email": "594383769@qq.com",
            "openBtnBackground": "#333",
            "shareFooterBackground": "#fff",
            "theme": "#40b290",
            "downloadUrl": "//android.uhomecp.com/ganglian/download.html"
        },
        "ZZPMBK": {
            "appName": "楼掌门物管",
            "company": "",
            "companyShortName": "国贸物业",
            "appNameColor": "#333",
            "slogan": "",
            "sloganColor": "#666",
            "bonuseSysName": "",
            "coinName": "",
            "logoIcon": "https://betapic.uhomecp.com/logo/zzpmbk.png",
            "openBtnBackground": "#fcbd30",
            "shareFooterBackground": "#fff",
            "downloadUrl": "http://android.uhomecp.com/zhongzheng/download_admin.html"
        },
        "SEGIPAY": {
            "appName": "企云收款",
            "company": "企云收款",
            "companyShortName": "企云收款",
            "logoIcon": "",
            "openBtnBackground": "#333",
            "downloadUrl": "",
            "email": "segi@segimail.com",
            "tel": "0755-86700725"
        },
        "ZHONGHAIPAY": {
            "appName": "中海智能收费",
            "company": "中海智能收费",
            "companyShortName": "中海智能收费",
            "logoIcon": "",
            "openBtnBackground": "#333",
            "downloadUrl": "",
            "email": "segi@segimail.com",
            "tel": "0755-86700725"
        },
        "BOEBK": {
            "appName": "BOE服务",
            "company": "",
            "companyShortName": "京东方物业",
            "appNameColor": "#333",
            "slogan": "",
            "sloganColor": "#666",
            "bonuseSysName": "",
            "coinName": "",
            "logoIcon": "https://betapic.uhomecp.com/logo/boebk.png",
            "openBtnBackground": "#fcbd30",
            "shareFooterBackground": "#fff",
            "downloadUrl": "http://android.uhomecp.com/boe/download_admin.html"
        },
        "KGWBK": {
            "appName": "空港管家",
            "company": "空港物业服务有限公司",
            "companyShortName": "空港新城企业总部",
            "appNameColor": "#333",
            "slogan": "",
            "sloganColor": "#666",
            "bonuseSysName": "",
            "coinName": "",
            "logoIcon": "https://betapic.uhomecp.com/logo/boebk.png",
            "openBtnBackground": "#fcbd30",
            "shareFooterBackground": "#fff",
            "downloadUrl": "http://android.uhomecp.com/boe/download_admin.html"
        },
        "megahope": {
            "appName": "美格宏",
            "company": "深圳市万家好实业集团有限公司",
            "companyShortName": "万家好",
            "email": "it@megahope-group.com",
            "appNameColor": "#333",
            "slogan": "服务万家·万家安好",
            "sloganColor": "#666",
            "bonuseSysName": "积分商城",
            "coinName": "积分",
            "logoIcon": "https://betapic.uhomecp.com/logo/megahope_logo.png",
            "theme": "#e95513",
            "openBtnBackground": "#e95513",
            "shareFooterBackground": "#fff",
            "downloadUrl": "https://android.uhomecp.com/megahope/download.html"
        },
        "ahhdwy": {
            "developer": "安徽华地物业管理服务有限公司",
            "corporation": "管玉社",
            "appName": "华地汇",
            "company": "安徽华地物业管理服务有限公司",
            "companyShortName": "华地汇",
            "email": "614548038@qq.com",
            "tel": "0551-65637069",
            "appNameColor": "#333",
            "slogan": "家的情怀",
            "sloganColor": "#666",
            "theme": "#c5261d",
            "bonuseSysName": "积分商城",
            "coinName": "积分",
            "logoIcon": "https://betapic.uhomecp.com/logo/ahhdwy.png",
            "openBtnBackground": "#c5261d",
            "shareFooterBackground": "#fff",
            "downloadUrl": "http://android.uhomecp.com/ahhdwy/download.html"
        },
        "yongwei": {
            "appName": "永客会",
            "company": "郑州市永威物业服务有限公司",
            "corporation": "李红建",
            "email": "569729807@qq.com",
            "tel": "0371-58666657",
            "developer": "郑州市永威物业服务有限公司",
            "companyShortName": "永威",
            "appNameColor": "#333",
            "slogan": "永威精致生活服务平台",
            "sloganColor": "#666",
            "bonuseSysName": "积分商城",
            "coinName": "积分",
            "logoIcon": "https://betapic.uhomecp.com/logo/yongwei.png",
            "openBtnBackground": "#7D7D7D",
            "shareFooterBackground": "#fff",
            "downloadUrl": "http://android.uhomecp.com/yongwei/download.html",
            "theme": "#7D7D7D"
        },
        "yongweibk": {
            "appName": "WE-i",
            "company": "郑州市永威物业服务有限公司",
            "corporation": "李红建",
            "email": "569729807@qq.com",
            "tel": "0371-58666657",
            "developer": "郑州市永威物业服务有限公司",
            "companyShortName": "永威",
            "appNameColor": "#333",
            "slogan": "永威精致生活服务平台",
            "sloganColor": "#666",
            "bonuseSysName": "",
            "coinName": "",
            "logoIcon": "https://betapic.uhomecp.com/logo/yongweibk.png",
            "openBtnBackground": "#3E5DE1",
            "shareFooterBackground": "#fff",
            "downloadUrl": "http://android.uhomecp.com/yongwei/download_admin.html"
        }
    },
    "customPortal": {
        "resName": "工作台",
        "url": "/web/project-management-and-control/#/divsManager/projectManagementAndControl",
        "popeCode": "projectControl_Workbench",
        "enableHelpCenter": true,
        "disableQRCode": false,
        "disableMemo": false,
        "disableNotice": false,
        "disableDialPanel": false,
        "disableFastEntry": false,
        "disableAd": false,
        "disableInfo": false,
        "disablePrivacy": false,
        "enableThirdParty": false,
        "disableAppLogin": false,
        "loginTitleZh": "资产管理系统",
        "loginTitleEn": "",
        "loginTopBg": "",
        "loginBottomBg": "",
        "loginCopyright": "",
        "loginRecord": "",
        "loginIcpURL": "",
        "disableLoginFooter": false,
        "loginHeadTitle": "",
        "helpCenterName": "helpCenter",
        "enableMenuSearch": true,
        "enableCallShow": true,
        "callShowUrl": "https://www.baidu.com",
        "disableAnnunciate": 1,
        "customMenu": [
            {
                "name": "客户管理",
                "tabName": "业主管理",
                "enName": "Customer",
                "link": "/uhomecp-customer/custViewController/custViewPage?pageType=custOwnerView",
                "isReady": 0,
                "color": "#02A5AB",
                "target": ""
            },
            {
                "name": "客服管理",
                "tabName": "工单查询",
                "enName": "Service",
                "link": "/order-web/#/home/orderQuery",
                "isReady": 0,
                "color": "#a35bfb",
                "target": ""
            },
            {
                "name": "综合巡查",
                "tabName": "任务实时查询",
                "enName": "Patrol",
                "link": "/uhomecp-patrol/patrolSpotInstHis/patrolInstHisMgrIndex",
                "isReady": 0,
                "color": "#FFAC3E",
                "target": ""
            },
            {
                "name": "设备管理",
                "tabName": "设备任务实时查询",
                "enName": "Rquipment",
                "link": "/uhomecp-equipment/equipmentPlanDetailHisController/equipmentPlanDetailHis",
                "isReady": 0,
                "color": "FF93A1",
                "target": ""
            },
            {
                "name": "品质管理",
                "tabName": "核查任务",
                "enName": "Quality",
                "link": "/quality-check/#/qualityMission",
                "isReady": 0,
                "color": "#3186FB",
                "target": ""
            },
            {
                "name": "二装管理",
                "tabName": "工程申请",
                "enName": "Engineering",
                "link": "/transaction-jdf/#/transaction/engineeringManagement",
                "isReady": 0,
                "color": "#02A5AB",
                "target": ""
            },
            {
                "name": "库存管理",
                "tabName": "订单查询",
                "enName": "Inventory",
                "link": "/inventory-management/#/orderQuery",
                "isReady": 0,
                "color": "#a35bfb",
                "target": ""
            },
            {
                "name": "小程序管理",
                "tabName": "社区资讯",
                "enName": "Information",
                "link": "/web/community-news-web/#/home/newsList",
                "isReady": 0,
                "color": "#FFAC3E",
                "target": ""
            },
            {
                "name": "通行管理",
                "tabName": "商写常客通行记录",
                "enName": "Access",
                "link": "/web/visitor/#/resident-access-record",
                "isReady": 0,
                "color": "#FF93A1",
                "target": ""
            },
            {
                "name": "梯控管理",
                "tabName": "门禁档案",
                "enName": "Access control",
                "link": "/web/access-control-management-web/#/home/doorRecord",
                "isReady": 0,
                "color": "#3186FB",
                "target": ""
            },
            {
                "name": "会务经营",
                "tabName": "订单管理",
                "enName": "Conference",
                "link": "/web/divsmanage-web/#/divsManager/order",
                "isReady": 0,
                "color": "#02A5AB",
                "target": ""
            },
            {
                "name": "报表中心",
                "tabName": "服务分析",
                "enName": "Analytic",
                "link": "/web/analytic/#/service-analytic/index",
                "isReady": 0,
                "color": "#a35bfb",
                "target": ""
            }
        ]
    }
}